import { CardProps } from "../types";

export const defaultData: CardProps[] = [
  {
    id: "1",
    status: "todo",
    title: "Card 1",
    description: "This is the first card",
    tags: ["web", "app"],
    dueDate: "2024-06-30",
  },
  {
    id: "2",
    status: "todo",
    title: "Card 2",
    description: "This is the second card",
    tags: ["web"],
    dueDate: "2024-07-15",
  },
  {
    id: "3",
    status: "progress",
    title: "Card 3",
    description: "This is the third card",
    tags: ["app", "mobile"],
    dueDate: "2024-08-01",
  },
  {
    id: "4",
    status: "done",
    title: "Card 4",
    description: "This is the fourth card",
    tags: ["web", "app"],
    dueDate: "2024-09-10",
  },
  {
    id: "5",
    status: "pending",
    title: "Card 5",
    description: "This is the fifth card",
    tags: ["web"],
    dueDate: "2024-10-05",
  },
  {
    id: "6",
    status: "done",
    title: "Card 6",
    description: "This is the sixth card",
    tags: ["mobile", "app"],
    dueDate: "2024-10-05",
  },
  {
    id: "7",
    status: "progress",
    title: "Card 7",
    description: "This is the seventh card",
    tags: ["mobile"],
    dueDate: "2024-07-15",
  },
  {
    id: "8",
    status: "done",
    title: "Card 8",
    description: "This is the eight card",
    tags: ["mobile", "web"],
    dueDate: "2024-11-02",
  },
  {
    id: "9",
    status: "todo",
    title: "Card 9",
    description: "This is the ninth card",
    tags: ["mobile"],
    dueDate: "2024-12-07",
  },
];
